name: auto-changelog-generator

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the code ------------------------------------------------------------------------------ #
      - name: Checkout Code
        uses: actions/checkout@v2

      # Update the CHANGELOG.md file ------------------------------------------------------------------- #
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      # Build PDF & HTML Documentation -------------------------------------------------------------------- #
      - name: Build PDF Documentation
        uses: addnab/docker-run-action@v3
        with:
          image: hsiangjenli/sphinx-doc:2026-02-06
          options: -v ${{ github.workspace }}:/workspace
          run: |
            uv sync 
            uv build
            uv export --format cyclonedx1.5 --output-file sbom.json
            uv sync --group sphinx
            cd docs && make simplepdf
            cd docs && make html

      # Save SBOM to Release ----------------------------------------------------------------------- #
      - name: Save SBOM to Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: sbom.json

      # Create Release --------------------------------------------------------------------------------- #
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          artifacts: |
            dist/*.whl
            dist/*.tar.gz
            docs/build/simplepdf/*.pdf

      # Commit ----------------------------------------------------------------------------------------- #
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md

      # Deploy ----------------------------------------------------------------------------------------- #
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
